### PR TITLE
Adds basic unit tests

### LINKED ISSUE #3: Unit tests
1. decouple main logic from the actual wordpress functions
2. validate logic

### PR DESCRIPTION
**Pull request by austinpray**
Right now I'm trying to unit test the current functionality without taking care of https://github.com/roots/bedrock-autoloader/issues/5 or https://github.com/roots/bedrock-autoloader/issues/4. Essentially add unit tests without touching anything in the `src/` directory.

It might prove impossible: we might have to refactor this guy to make testing possible at all.

closes https://github.com/roots/bedrock-autoloader/issues/3

### CODE REVIEW

**Comment by austinpray** [comment]
@aaemnnosttv you might be interested in this guy. I'm sure you can see where I am running into trouble.

**Comment by aaemnnosttv** [comment]
See #19 😄

**Review by austinpray — COMMENTED** [review]
Way more is needed to make these tests more useful. We can iterate on master from here.

**Review by swalkinshaw — APPROVED** [review]
I'm good with this as a start 👍

**Review by tangrufus — APPROVED** [review]

**Comment by tangrufus** [comment]
Question: Does github action support testing on multiple PHP versions?

**Comment by vinkla** [comment]
> Question: Does github action support testing on multiple PHP versions?

[Yes, it is possible.](https://github.com/wordplate/extended-acf/blob/0e2cbc3ba9e5d7ecf30d864175aa4e18965744c4/.github/workflows/ci.yml#L11)

**Comment by austinpray** [comment]
@vinkla wanna add that?

**Comment by vinkla** [comment]
Done #22

**Pull request merged**
